[workspace]
members = [
    "arith/assert_field_equals",
    "arith/add_mul",
    "arith/return_mul",
    "arith/assert_mul",
    "arith/loop",
    "arith/if",
    "arith/u1_comparison",
    "arith/u2_comparison",
    "arith/u8_comparison",
    "arith/pythagorean_triplet",
    "circuits/poseidon",
    "circuits/rlp",
    "circuits/keccak",
    "circuits/keccak_2x",
    "circuits/recursive",
    "circuits/recursive_2x",
]
default-member = "circuits/keccak"
