[workspace]
members = [
    "circuits/add_mul",
    "circuits/mul_return",
    "circuits/mul_assert",
    "circuits/loop",
    "circuits/if",
    "circuits/poseidon",
    "circuits/rlp",
    "circuits/keccak",
    "circuits/keccak_2x",
    "circuits/recursive",
    "circuits/recursive_2x",
    "noir_tests/1327_concrete_in_generic",
    "noir_tests/1_mul",
    "noir_tests/2_div",
    "noir_tests/3_add",
    "noir_tests/4_sub",
    "noir_tests/5_over",
    "noir_tests/6",
    "noir_tests/6_array",
    "noir_tests/7",
    "noir_tests/7_function",
    "noir_tests/arithmetic_binary_operations",
    "noir_tests/array_dynamic",
    "noir_tests/array_eq",
    "noir_tests/array_len",
    "noir_tests/array_neq",
    "noir_tests/array_sort",
    "noir_tests/assert",
    "noir_tests/assert_statement",
    "noir_tests/assign_ex",
    "noir_tests/bit_and",
    "noir_tests/bit_shifts_comptime",
    "noir_tests/bit_shifts_runtime",
    "noir_tests/blake3",
    "noir_tests/bool_not",
    "noir_tests/bool_or",
    "noir_tests/brillig_acir_as_brillig",
    "noir_tests/brillig_array_eq",
    "noir_tests/brillig_arrays",
    "noir_tests/brillig_blake2s",
    "noir_tests/brillig_blake3",
    "noir_tests/brillig_calls",
    "noir_tests/brillig_calls_array",
    "noir_tests/brillig_calls_conditionals",
    "noir_tests/brillig_conditional",
    "noir_tests/brillig_cow",
    "noir_tests/brillig_ecdsa_secp256k1",
    "noir_tests/brillig_ecdsa_secp256r1",
    "noir_tests/brillig_fns_as_values",
    "noir_tests/brillig_hash_to_field",
    "noir_tests/brillig_identity_function",
    "noir_tests/brillig_keccak",
    "noir_tests/brillig_loop",
    "noir_tests/brillig_nested_arrays",
    "noir_tests/brillig_not",
    "noir_tests/brillig_pedersen",
    "noir_tests/brillig_recursion",
    "noir_tests/brillig_references",
    "noir_tests/brillig_scalar_mul",
    "noir_tests/brillig_schnorr",
    "noir_tests/brillig_sha256",
    "noir_tests/brillig_slices",
    "noir_tests/brillig_to_be_bytes",
    "noir_tests/brillig_to_bits",
    "noir_tests/brillig_to_le_bytes",
    "noir_tests/brillig_top_level",
    "noir_tests/brillig_unitialised_arrays",
    "noir_tests/cast_bool",
    "noir_tests/closures_mut_ref",
    "noir_tests/conditional_1",
    "noir_tests/conditional_2",
    "noir_tests/conditional_regression_421",
    "noir_tests/conditional_regression_661",
    "noir_tests/conditional_regression_short_circuit",
    "noir_tests/custom_entry",
    "noir_tests/debug_logs",
    "noir_tests/distinct_keyword",
    "noir_tests/ecdsa_secp256k1",
    "noir_tests/ecdsa_secp256r1",
    "noir_tests/eddsa",
    "noir_tests/field_attribute",
    "noir_tests/generics",
    "noir_tests/global_consts",
    "noir_tests/hash_to_field",
    "noir_tests/higher_order_functions",
    "noir_tests/if_else_chain",
    "noir_tests/import",
    "noir_tests/integer_array_indexing",
    "noir_tests/keccak256",
    "noir_tests/main_bool_arg",
    "noir_tests/merkle_insert",
    "noir_tests/missing_closure_env",
    "noir_tests/modules",
    "noir_tests/modules_more",
    "noir_tests/modulus",
    "noir_tests/nested_array_dynamic",
    "noir_tests/nested_array_in_slice",
    "noir_tests/nested_arrays_from_brillig",
    "noir_tests/operator_overloading",
    "noir_tests/pedersen_check",
    "noir_tests/pedersen_commitment",
    "noir_tests/pedersen_hash",
    "noir_tests/poseidon_bn254_hash",
    "noir_tests/poseidonsponge_x5_254",
    "noir_tests/pred_eq",
    "noir_tests/prelude",
    "noir_tests/references",
    "noir_tests/regression",
    "noir_tests/regression_2660",
    "noir_tests/regression_2854",
    "noir_tests/regression_3394",
    "noir_tests/regression_3607",
    "noir_tests/regression_3889",
    "noir_tests/regression_mem_op_predicate",
    "noir_tests/regression_method_cannot_be_found",
    "noir_tests/schnorr",
    "noir_tests/sha256",
    "noir_tests/sha2_byte",
    "noir_tests/side_effects_constrain_array",
    "noir_tests/signed_arithmetic",
    "noir_tests/signed_comparison",
    "noir_tests/signed_division",
    "noir_tests/simple_2d_array",
    "noir_tests/simple_add_and_ret_arr",
    "noir_tests/simple_bitwise",
    "noir_tests/simple_comparison",
    "noir_tests/simple_mut",
    "noir_tests/simple_not",
    "noir_tests/simple_print",
    "noir_tests/simple_program_addition",
    "noir_tests/simple_radix",
    "noir_tests/simple_shield",
    "noir_tests/simple_shift_left_right",
    "noir_tests/slice_dynamic_index",
    "noir_tests/slices",
    "noir_tests/strings",
    "noir_tests/struct_array_inputs",
    "noir_tests/struct_fields_ordering",
    "noir_tests/submodules",
    "noir_tests/to_bytes_consistent",
    "noir_tests/to_le_bytes",
    "noir_tests/traits_in_crates_1",
    "noir_tests/traits_in_crates_2",
    "noir_tests/tuple_inputs",
    "noir_tests/tuples",
    "noir_tests/type_aliases",
    "noir_tests/unconstrained_empty",
    "noir_tests/unsafe_range_constraint",
    "noir_tests/xor",
]
default-member = "circuits/keccak"
