[workspace]
members = [
    "circuits/add_mul",
    "circuits/mul_return",
    "circuits/mul_assert",
    "circuits/loop",
    "circuits/if",
    "circuits/poseidon",
    "circuits/rlp",
    "circuits/keccak",
    "circuits/keccak_2x",
    "circuits/recursive",
    "circuits/recursive_2x",
    "noir_tests/array_eq",
    "noir_tests/array_len",
    "noir_tests/array_sort",
    "noir_tests/assert",
    "noir_tests/assert_statement",
    "noir_tests/assign_ex",
    "noir_tests/bool_not",
    "noir_tests/bool_or",
    "noir_tests/brillig_array_eq",
    "noir_tests/brillig_arrays",
    "noir_tests/brillig_blake3",
    "noir_tests/brillig_conditional",
    "noir_tests/brillig_cow",
    "noir_tests/brillig_hash_to_field",
    "noir_tests/brillig_identity_function",
    "noir_tests/brillig_loop",
    "noir_tests/brillig_nested_arrays",
    "noir_tests/brillig_oracle",
    "noir_tests/brillig_pedersen",
    "noir_tests/brillig_references",
    "noir_tests/brillig_scalar_mul",
    "noir_tests/brillig_schnorr",
    "noir_tests/brillig_slices",
    "noir_tests/brillig_to_be_bytes",
    "noir_tests/brillig_to_bits",
    "noir_tests/brillig_to_bytes_integration",
    "noir_tests/brillig_to_le_bytes",
    "noir_tests/brillig_top_level",
    "noir_tests/brillig_unitialised_arrays",
    "noir_tests/cast_bool",
    "noir_tests/closures_mut_ref",
    "noir_tests/custom_entry",
    "noir_tests/debug_logs",
    "noir_tests/distinct_keyword",
    "noir_tests/generics",
    "noir_tests/higher_order_functions",
    "noir_tests/import",
    "noir_tests/main_bool_arg",
    "noir_tests/missing_closure_env",
    "noir_tests/mock_oracle",
    "noir_tests/modules",
    "noir_tests/modules_more",
    "noir_tests/nested_arrays_from_brillig",
    "noir_tests/pred_eq",
    "noir_tests/prelude",
    "noir_tests/references",
    "noir_tests/simple_2d_array",
    "noir_tests/simple_add_and_ret_arr",
    "noir_tests/simple_mut",
    "noir_tests/simple_not",
    "noir_tests/simple_print",
    "noir_tests/simple_program_addition",
    "noir_tests/simple_radix",
    "noir_tests/struct",
    "noir_tests/struct_array_inputs",
    "noir_tests/struct_fields_ordering",
    "noir_tests/submodules",
    "noir_tests/to_bytes_consistent",
    "noir_tests/trait_impl_base_type",
    "noir_tests/traits_in_crates_1",
    "noir_tests/traits_in_crates_2",
    "noir_tests/tuples",
    "noir_tests/type_aliases",
    "noir_tests/unconstrained_empty",
]
default-member = "circuits/keccak"
