[workspace]
members = [
    "circuits/add_mul",
    "circuits/mul_return",
    "circuits/mul_assert",
    "circuits/loop",
    "circuits/if",
    "circuits/poseidon",
    "circuits/rlp",
    "circuits/keccak",
    "circuits/keccak_2x",
    "circuits/recursive",
    "circuits/recursive_2x",
]
default-member = "circuits/keccak"
